### PR TITLE
Spelling: ellipsis … Fixes #267

### LINKED ISSUE #267: Substitude '...' (3 dots) for proper unicode ellipsis symbol
Textstrings should use the proper unicode char instead of three dots.

On Linux the ellipsis char may be produced by ``AltGr + .``.

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by elbenfreund** [comment]
Thank you for your contribution. This should fix #267 , doesn't it?

Can you please squash both commits into one and provide a brief [commit message](https://github.com/projecthamster/hamster-shell-extension/blob/develop/docs/styleguide.rst#committing-and-commit-messages)

**Comment by comradekingu** [comment]
@elbenfreund Like so?

**Comment by mwilck** [comment]
This is incomplete. We must do the same thing in translations, too. I've pushed this with an additional patch on top to the [ellipsis](https://github.com/projecthamster/hamster-shell-extension/commits/ellipsis) branch.

@comradekingu, I can create a PR for your branch here, or supersede this PR with a new one. How would you like to proceed?

**Comment by mwilck** [comment]
@comradekingu, ping?

**Comment by comradekingu** [comment]
@mwilck Any is fine. I think I was just translating or using this and noticed improvements to be made.

**Pull request closed without merging**
