### PR TITLE
Update todaysFactsWidget.js for Gnome Shell 46 compatibility

### PR DESCRIPTION
**Pull request by piio**
Additional change for Gnome 46

### CODE REVIEW

**Comment by hedayat** [comment]
Thank you for the PR.

Have you got errors from this line? This change was actually reverted in this commit: https://github.com/projecthamster/hamster-shell-extension/commit/cc353e25e01b0bbc51afe5067bf3df2b25c082ad 

It was already part of PR #367, but reverted in the above commit. It is supposed to work fine on both Gnome 45 & 46.

I've not tested the final develop yet, so I cannot comment on it. 

@mwilck

**Comment by hedayat** [comment]
OK, I just tested the current `develop` branch and the extension exists immediately. Looks like at least in shell, `add_actor` is not supported even for `ScrollView`.

**Comment by mwilck** [comment]
> OK, I just tested the current develop branch and the extension exists immediately. Looks like at least in shell, add_actor is not supported even for ScrollView.

Works fine here.

**Comment by mwilck** [comment]
This change can't be applied, it breaks GNOME 45.

**Comment by mwilck** [comment]
Please try [this patch](https://github.com/projecthamster/hamster-shell-extension/issues/362#issuecomment-2039855578).

**Comment by mwilck** [comment]
Which version of GNOME 46 and clutter are you guys using?

**Comment by hedayat** [comment]
> Which version of GNOME 46 and clutter are you guys using?

Well, the result is somewhat surprising:
```
% rpm -q gnome-shell clutter
gnome-shell-46.0-1.fc40.x86_64
package clutter is not installed
```

Well, no clutter is installed at all.

**Comment by hedayat** [comment]
> Please try [this patch](https://github.com/projecthamster/hamster-shell-extension/issues/362#issuecomment-2039855578).

Can't test right now, but will let you know the results soon. I guess it will work though.

**Comment by mwilck** [comment]
> Well, no clutter is installed at all.

Same here, sorry. There's just "libclutter" and "libclutter-gst". I confess I don't know how these dependencies work.

**Comment by mwilck** [comment]
Upstream has also suggested that we use the shell version check. If it works for you, I'll push it, even though I wanted to avoid this kind of thing at least for the first shell version bump after the largish changes for 45 :-/

**Comment by hedayat** [comment]
> > Well, no clutter is installed at all.
> 
> Same here, sorry. There's just "libclutter" and "libclutter-gst". I confess I don't know how these dependencies work.

I do have these two on Fedora 39 (Gnome 45),  but on Fedora 40 with Gnome 46, even these are not installed by default anymore. BTW, I don't know either :)



> Upstream has also suggested that we use the shell version check. If it works for you, I'll push it, even though I wanted to avoid this kind of thing at least for the first shell version bump after the largish changes for 45 :-/

Sure, I'm now on another system with Gnome 45. I'll test it under Gnome 46 and let you know.

Yeah, we didn't expect another compatibility break so soon :D

**Comment by mwilck** [comment]
@piio perhaps you could test with https://github.com/projecthamster/hamster-shell-extension/issues/362#issuecomment-2039855578?

Like @hedayat, I am pretty sure it will work. But I'd like to have a confirmation because the current version works for me, while it doesn't for you, it would be good to have this confirmed.

**Comment by hedayat** [comment]
> @piio perhaps you could test with [#362 (comment)](https://github.com/projecthamster/hamster-shell-extension/issues/362#issuecomment-2039855578)?
> 
> Like @hedayat, I am pretty sure it will work. But I'd like to have a confirmation because the current version works for me, while it doesn't for you, it would be good to have this confirmed.

OK, I tested and it works fine under Gnome 46.

**Comment by mwilck** [comment]
Thanks. Pushed e3a4cb1 to `develop` now.

**Comment by piio** [comment]
e3a4cb15063ab8ab6839fecee805a42b27914a2a works correctly for me, thank you!

**Pull request closed without merging**
