### PR TITLE
[#103] Provide a generic class on search input

### LINKED ISSUE #103: autocomplete color in entry field unreadable
With the last update of the extension, the entry field for new tasks has no longer a bright background. If I start entering a new tast, the autocomplete mechanism shows me a suggestion with a unreadable color. It is a bright green text on a white background. As soon a I move the cursor to the end of the text, it is readable again.
This makes the autocomplete useless, since I have to choose between several more or less unique task names.
I have a sceenshot, but I can't attach it to this issue ("Something went really wrong, and we can’t process that file.").

### PR DESCRIPTION
**Pull request by camlafit**
* Set a style on input search following theme style

Fixes #103

### CODE REVIEW

**Comment by camlafit** [comment]
Hi 

Any news about this suggestion and new version was provided. Can you merge it @toupeira ?

**Comment by elbenfreund** [comment]
@border0464111 If you got time, can you have a look at this please? Looks alright.

**Comment by border0464111** [comment]
Tested, all good for me too :D

**Comment by elbenfreund** [comment]
@border0464111 Feel free to merge! :)

**Comment by camlafit** [comment]
Oh yeah :)

Great notice and when the PR will be applied ?

**Comment by elbenfreund** [comment]
If boarder does not have time today I will merge it by evening. But in general I would like him to do this as he is taking over as maintainer of the extension :)

Thank you for the commit! You don't happen to be interested in joining our little hamster crew are you? :)

**Comment by camlafit** [comment]
Great new

Actually I use hamster daily, with gnome extension is very usefull.
I'm interessted also about redmine and toggl bridge.
If I can help with plesasure :)
​

**Comment by elbenfreund** [comment]
While integration with other time tracking services is part of our mid/long term goals I would not expect them to be ready this year :(
Right now our focus is on bringing the project in shape in general. As we are revisiting a lot of the codebase, the most valuable thing right now is another set of eyes for code reviews. So if you feel like joining us, please let me know.

**Comment by elbenfreund** [comment]
@camlafit 
I just stumbled upon [hamster-bridge](https://github.com/kraiz/hamster-bridge). Maybe this is of some use for you?

**Comment by camlafit** [comment]
Hi

yes hamster-bridge looks interesting, I've found an another project with same purpose.

But i come about an other pb :) I've updated extensions from https://extensions.gnome.org and last updates are not presents (as this PR). Is it normal ? I don't know how gnome.org provide update.

**Comment by elbenfreund** [comment]
The current ``development`` branch has not been packaged to be placed on éxtensions.gnome.org.
I would like to get this wrapped up in the near future but this depends a bit on @border0464111 who is officially maintaining the extension and should look over a couple of open pull requests before we can package a new release.

Please Frederic, if you get this let me know what your timeline / available resources are the next few weeks so we can plan around what is and what is not possible.

**Pull request merged**
