### PR TITLE
Update README.st

### PR DESCRIPTION
**Pull request by DirkHoffmann**
Compatibility with gnome-shell 3.30 according to #301

### CODE REVIEW

**Comment by DirkHoffmann** [comment]
The latest gnome-shell version known to work is 3.34. 
I have to update that before merging.

**Comment by DirkHoffmann** [comment]
I assign you in turn, @mwilck. But probably we have to bump the "last supported version" number to 3.36 anyway by now.

**Comment by mwilck** [comment]
Can't we just link to `metadata.json`, or the commit history? Having to update the README for every new GNOME shell release looks like tedious, pointless, easily-forgotten work to me. The README has obviously been wrong for years.

**Comment by mwilck** [comment]
IOW, I propose not to mention an explicit GNOME shell version in the README at all. Rather, we should provide new users guidance how to figure out the right version. We should point them at

 * E.G.O. (assuming that we'll solve the "who is going to upload" question some time soon)
 * `metadata.json`
 * [the commit history](https://github.com/projecthamster/hamster-shell-extension/commits/develop)
 * possibly, [the sticky issue about GNOME versions](https://github.com/projecthamster/hamster-shell-extension/issues/327) and [the list of open PRs](https://github.com/projecthamster/hamster-shell-extension/pulls)

**Review by mwilck — APPROVED** [review]
Ok, I guess rather than discussing, let's simply pull this. We can try to make the README GNOME version-agnostic later.

**Pull request merged**
